name: indiapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  animate_do: ^3.3.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^13.0.2
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  local_auth: ^2.3.0
  firebase_auth: ^5.3.4
  flutter_animate: ^4.5.2
  image_cropper: ^8.1.0

  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
